---
- hosts: server
  remote_user: root  
  vars_files:
    - server_vars.yml
  tasks:
    - name: copy hosts_ip
      template: src=/etc/hosts dest=/etc/hosts
      tags:
        - copy hosts_ip

    - name:  check install release
      shell: "rpm -qi zabbix-release-3.4-1.el7.centos.noarch"
      register: result
      ignore_errors: True
      tags:
        - check

    - name: install zabbix-release.rpm
      shell: "rpm -ivh http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm"
      when: result.rc == 1
      tags:
        - install

    - name: install package
      yum: pkg={{ item }} state=latest
      with_items:
        - mariadb
        - mariadb-server
        - zabbix-server-mysql
        - zabbix-web-mysql
        - zabbix-agent
        - MySQL-python
      tags:
        - install pkg

    - name: enable && restart mariadb
      shell: "systemctl enable mariadb && systemctl restart mariadb"
      tags:
        - restart mariadb
      notify:
        - restart mariadb

    - name: Mysql | create database
      mysql_db: name=mark state=present encoding=utf8 collation=utf8_bin
      tags:
        - mysql

    - name: Mysql | create database user
      mysql_user: name=mliu password=123456 priv=mark.*:ALL state=present
      tags:
        - mysql

    - name: zcat mysql
      shell: "zcat /usr/share/doc/zabbix-server-mysql-3.4.4/create.sql.gz | mysql -umliu -p123456 mark"
      tags:
        - zcat mysql

    - name: close selinux
      shell: "sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' {{selinux_file}} && setenforce 0"
      tags:
        - close selinux

    - name: set firewall
      shell: "firewall-cmd --add-port={80/tcp,10051/tcp} --permanent && firewall-cmd --reload"
      tags:
        - firewall

    - name: copy zabbix_server.conf
      template: src=zabbix_server.conf.j2 dest=/etc/zabbix/zabbix_server.conf
      tags:
        - copy config
      notify:
        - restart zabbix_server

    - name: copy zabbix_agentd.conf
      template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
      tags:
        - copy config
      notify:
        - restart zabbix_agentd

    - name: copy zabbix.conf
      template: src=zabbix.conf.j2 dest=/etc/httpd/conf.d/zabbix.conf
      tags:
        - copy config
      notify:
        - restart httpd

  handlers:
    - name: restart mariadb
      service: name=mariadb state=restarted enabled=yes

    - name: restart httpd
      service: name=httpd state=restarted

    - name: restart zabbix_server
      service: name=zabbix-server state=restarted enabled=yes

    - name: restart zabbix_agentd
      service: name=zabbix-agent state=restarted
