
---
- hosts: agent
  remote_user: root
  vars_files:
    - agent_vars.yml
  tasks:
    - name: copy hosts_ip
      template: src=/etc/hosts dest=/etc/hosts
      tags:
        - copy hosts_ip

    - name: check install release
      shell: "rpm -qi zabbix-release-3.4-1.el7.centos.noarch"
      register: result
      ignore_errors: True
      tags:
        - check

    - name: "install zabbix-release.rpm"
      shell: "rpm -ivh http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm"
      when: result.rc == 1      
      tags:
        - install

    - name: "install zabbix-agent"
      yum: name=zabbix-agent state=present
      tags:
        - install_agent

    - name: copy zabbix_agentd.conf
      template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
      tags:
        - copy config

    - name: enable & restart agent
      shell: "systemctl enable zabbix-agent"
      tags:
        - enable
      notify:
        - restart zabbix_agentd  

    - name: "set firewalld"
      shell: "firewall-cmd --permanent --add-port=10050/tcp && firewall-cmd --reload"
      tags:
        - firewalld

  handlers:
    - name: restart zabbix_agentd
      service: name=zabbix-agent state=restarted enabled=yes
